# Generated by Django 4.0.1 on 2022-04-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_desk', '0002_hospitalbills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalBills',
        ),
    ]
