# Generated by Django 4.0.1 on 2022-04-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_desk', '0004_hospitalbills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalbills',
            name='AmountPaid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospitalbills',
            name='FullyPaidDate',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='hospitalbills',
            name='TotalBill',
            field=models.IntegerField(default=0),
        ),
    ]
