# Generated by Django 4.0.1 on 2022-04-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_desk', '0005_alter_hospitalbills_amountpaid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalbills',
            name='FullyPaidDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
