# Generated by Django 4.0.1 on 2022-04-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_desk', '0006_alter_hospitalbills_fullypaiddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalbills',
            name='BillerID',
        ),
    ]
