# Generated by Django 4.0.1 on 2022-04-10 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_desk', '0007_remove_hospitalbills_billerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalbills',
            name='FullyPaidDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
