# Generated by Django 4.0.1 on 2022-04-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_desk', '0009_biller_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='biller',
            name='Age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='biller',
            name='Salary',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='biller',
            name='Shift',
            field=models.IntegerField(default=None),
        ),
        migrations.DeleteModel(
            name='HospitalBills',
        ),
    ]
