# Generated by Django 4.0.1 on 2022-04-10 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0012_doctorpatientassignment'),
        ('billing_desk', '0010_biller_age_biller_salary_biller_shift_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalBills',
            fields=[
                ('TotalBill', models.IntegerField(default=0)),
                ('AmountPaid', models.IntegerField(default=0)),
                ('FullyPaidDate', models.DateTimeField(blank=True, null=True)),
                ('BillID', models.IntegerField(primary_key=True, serialize=False)),
                ('Appointment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='receptionist.doctorpatientassignment')),
            ],
        ),
    ]
