# Generated by Django 4.0.1 on 2022-04-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_desk', '0011_hospitalbills'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Biller',
        ),
        migrations.DeleteModel(
            name='HospitalBills',
        ),
    ]
