# Generated by Django 4.0.1 on 2022-04-10 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptionist', '0016_initial'),
        ('billing_desk', '0014_delete_biller_delete_hospitalbills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biller',
            fields=[
                ('BillerID', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=45)),
                ('password', models.CharField(default=None, max_length=45)),
                ('LastName', models.CharField(max_length=45)),
                ('EmailAddress', models.CharField(max_length=45)),
                ('PermantAddress', models.CharField(max_length=100)),
                ('Age', models.IntegerField(default=None)),
                ('Salary', models.IntegerField(default=None)),
                ('Shift', models.IntegerField(default=None)),
                ('BloodGroup', models.CharField(max_length=45)),
                ('contact', models.CharField(default=None, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalBills',
            fields=[
                ('TotalBill', models.IntegerField(default=0)),
                ('AmountPaid', models.IntegerField(default=0)),
                ('FullyPaidDate', models.DateTimeField(blank=True, null=True)),
                ('BillID', models.IntegerField(primary_key=True, serialize=False)),
                ('Appointment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='receptionist.doctorpatientassignment')),
            ],
        ),
    ]
