# Generated by Django 4.0.1 on 2022-04-13 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing_desk', '0015_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalbills',
            name='Biller',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_desk.biller'),
        ),
    ]
