# Generated by Django 4.0.1 on 2022-04-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostician', '0002_diagnosis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
