# Generated by Django 4.0.1 on 2022-04-07 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0006_doctorpatientassignment'),
        ('diagnostician', '0003_delete_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('DiagnosticReportID', models.IntegerField(primary_key=True, serialize=False)),
                ('Appointment', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='receptionist.doctorpatientassignment')),
                ('Diagnostician', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='diagnostician.diagnostician')),
            ],
        ),
    ]
