# Generated by Django 4.0.1 on 2022-04-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostician', '0004_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='document',
            field=models.FileField(default=None, upload_to='labreport/'),
        ),
    ]
