# Generated by Django 4.0.1 on 2022-04-08 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostician', '0005_diagnosis_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='document',
            new_name='labreport',
        ),
    ]
