# Generated by Django 4.0.1 on 2022-04-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostician', '0007_diagnosis_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='labreport',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='labreportexists',
            field=models.BooleanField(default=False),
        ),
    ]
