# Generated by Django 4.0.1 on 2022-04-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostician', '0008_remove_diagnosis_labreport_diagnosis_labreportexists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='labreportexists',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='labreport',
            field=models.FileField(default=None, upload_to='labreport/'),
        ),
    ]
