# Generated by Django 4.0.1 on 2022-04-09 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0010_remove_doctorpatientassignment_hasmedicalreport'),
        ('diagnostician', '0010_alter_diagnosis_diagnostician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='bill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='totalbill',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='Appointment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='receptionist.doctorpatientassignment'),
        ),
    ]
