# Generated by Django 4.0.1 on 2022-04-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostician', '0011_diagnosis_bill_diagnosis_totalbill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostician',
            name='Age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diagnostician',
            name='Salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diagnostician',
            name='Shift',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diagnostician',
            name='PermantAddress',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
    ]
