# Generated by Django 4.0.1 on 2022-04-10 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0012_doctorpatientassignment'),
        ('diagnostician', '0012_diagnostician_age_diagnostician_salary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('DiagnosticReportID', models.IntegerField(primary_key=True, serialize=False)),
                ('labreport', models.BooleanField(default=False)),
                ('bill', models.BooleanField(default=False)),
                ('totalbill', models.IntegerField(default=0)),
                ('description', models.CharField(default=None, max_length=500)),
                ('Appointment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='receptionist.doctorpatientassignment')),
                ('Diagnostician', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diagnostician.diagnostician')),
            ],
        ),
    ]
