# Generated by Django 4.0.1 on 2022-04-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostician', '0015_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diagnosis',
        ),
        migrations.DeleteModel(
            name='Diagnostician',
        ),
    ]
