# Generated by Django 4.0.1 on 2022-04-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardclerk', '0002_warddetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WardDetails',
        ),
    ]
