# Generated by Django 4.0.1 on 2022-04-07 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0006_doctorpatientassignment'),
        ('patient', '0001_initial'),
        ('wardclerk', '0003_delete_warddetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BedNo', models.IntegerField()),
                ('Description', models.CharField(max_length=500)),
                ('JoinedDate', models.DateField()),
                ('LeftDate', models.DateField()),
                ('Appointment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='receptionist.doctorpatientassignment')),
                ('Patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('Ward', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wardclerk.ward')),
            ],
        ),
    ]
