# Generated by Django 4.0.1 on 2022-04-08 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0010_remove_doctorpatientassignment_hasmedicalreport'),
        ('wardclerk', '0004_warddetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warddetails',
            name='Patient',
        ),
        migrations.RemoveField(
            model_name='warddetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='warddetails',
            name='Appointment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='receptionist.doctorpatientassignment'),
        ),
        migrations.AlterField(
            model_name='warddetails',
            name='BedNo',
            field=models.IntegerField(default=None),
        ),
    ]
