# Generated by Django 4.0.1 on 2022-04-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardclerk', '0005_remove_warddetails_patient_remove_warddetails_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warddetails',
            name='JoinedDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='warddetails',
            name='LeftDate',
            field=models.DateTimeField(),
        ),
    ]
