# Generated by Django 4.0.1 on 2022-04-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardclerk', '0006_alter_warddetails_joineddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warddetails',
            name='totalbill',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warddetails',
            name='wardbill',
            field=models.BooleanField(default=False),
        ),
    ]
