# Generated by Django 4.0.1 on 2022-04-10 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0012_doctorpatientassignment'),
        ('wardclerk', '0008_wardclerk_age_wardclerk_salary_wardclerk_shift_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardDetails',
            fields=[
                ('Appointment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='receptionist.doctorpatientassignment')),
                ('wardbill', models.BooleanField(default=False)),
                ('totalbill', models.IntegerField(default=0)),
                ('BedNo', models.IntegerField(default=None)),
                ('Description', models.CharField(max_length=500)),
                ('JoinedDate', models.DateTimeField()),
                ('LeftDate', models.DateTimeField()),
                ('Ward', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wardclerk.ward')),
            ],
        ),
    ]
