# Generated by Django 4.0.1 on 2022-04-10 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0012_doctorpatientassignment'),
        ('wardclerk', '0009_warddetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warddetails',
            name='Appointment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='receptionist.doctorpatientassignment', unique=True),
        ),
    ]
