# Generated by Django 4.0.1 on 2022-04-10 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptionist', '0014_initial'),
        ('wardclerk', '0011_remove_wardclerk_ward_remove_warddetails_appointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('WardType', models.CharField(default='usual', max_length=45, primary_key=True, serialize=False)),
                ('WardCapacity', models.IntegerField()),
                ('Population', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WardDetails',
            fields=[
                ('Appointment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='receptionist.doctorpatientassignment', unique=True)),
                ('wardbill', models.BooleanField(default=False)),
                ('totalbill', models.IntegerField(default=0)),
                ('BedNo', models.IntegerField(default=None)),
                ('Description', models.CharField(max_length=500)),
                ('JoinedDate', models.DateTimeField()),
                ('LeftDate', models.DateTimeField()),
                ('Ward', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wardclerk.ward')),
            ],
        ),
        migrations.CreateModel(
            name='WardClerk',
            fields=[
                ('WardClerkID', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=45)),
                ('LastName', models.CharField(max_length=45)),
                ('EmailAddress', models.CharField(max_length=45)),
                ('PermantAddress', models.CharField(max_length=100)),
                ('Age', models.IntegerField(default=None)),
                ('Salary', models.IntegerField(default=None)),
                ('Shift', models.IntegerField(default=None)),
                ('BloodGroup', models.CharField(max_length=45)),
                ('contact', models.CharField(default=None, max_length=13)),
                ('password', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Ward', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wardclerk.ward')),
            ],
        ),
    ]
