# Generated by Django 4.0.1 on 2022-04-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardclerk', '0012_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wardclerk',
            name='Ward',
        ),
        migrations.RemoveField(
            model_name='warddetails',
            name='Appointment',
        ),
        migrations.RemoveField(
            model_name='warddetails',
            name='Ward',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
        migrations.DeleteModel(
            name='WardClerk',
        ),
        migrations.DeleteModel(
            name='WardDetails',
        ),
    ]
