# Generated by Django 3.2.7 on 2022-04-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientID', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=45)),
                ('LastName', models.CharField(max_length=45)),
                ('Age', models.IntegerField(default=None)),
                ('BloodGroup', models.CharField(max_length=45)),
                ('EmailAddress', models.CharField(max_length=45)),
                ('PermantAddress', models.CharField(max_length=100)),
                ('gender', models.CharField(default=None, max_length=40)),
                ('contact', models.CharField(default=None, max_length=40)),
                ('Height', models.CharField(default=None, max_length=40)),
                ('Weight', models.CharField(default=None, max_length=40)),
            ],
        ),
    ]
