# Generated by Django 4.0.1 on 2022-04-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Age',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Height',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Weight',
            field=models.IntegerField(default=None),
        ),
    ]
