# Generated by Django 4.0.1 on 2022-04-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_age_alter_patient_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Age',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Height',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Weight',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
