# Generated by Django 4.0.1 on 2022-04-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0015_delete_doctorpatientassignment_delete_receptionist'),
        ('patient', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
