# Generated by Django 4.0.1 on 2022-04-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0008_delete_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientID', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(default=None, max_length=50)),
                ('FirstName', models.CharField(max_length=45)),
                ('LastName', models.CharField(max_length=45)),
                ('Age', models.CharField(default=None, max_length=40)),
                ('BloodGroup', models.CharField(max_length=45)),
                ('EmailAddress', models.CharField(max_length=45)),
                ('PermantAddress', models.CharField(max_length=100)),
                ('gender', models.CharField(default=None, max_length=40)),
                ('contact', models.CharField(default=None, max_length=40)),
                ('Height', models.CharField(default=None, max_length=40)),
                ('Weight', models.CharField(default=None, max_length=40)),
            ],
        ),
    ]
