# Generated by Django 3.2.7 on 2022-04-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0002_doctorpatientassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpatientassignment',
            name='status',
            field=models.CharField(default='open', max_length=10),
        ),
    ]
