# Generated by Django 4.0.1 on 2022-04-07 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostician', '0003_delete_diagnosis'),
        ('billing_desk', '0003_delete_hospitalbills'),
        ('wardclerk', '0003_delete_warddetails'),
        ('medical_assistant', '0002_remove_medicalreport_appointment_and_more'),
        ('receptionist', '0004_alter_doctorpatientassignment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorPatientAssignment',
        ),
    ]
