# Generated by Django 4.0.1 on 2022-04-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0007_doctorpatientassignment_hasmedicalreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionist',
            name='Age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='Salary',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='Shift',
            field=models.IntegerField(default=None),
        ),
    ]
