# Generated by Django 4.0.1 on 2022-04-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0008_receptionist_age_receptionist_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorpatientassignment',
            name='status',
            field=models.CharField(default='Unattended', max_length=50),
        ),
    ]
