# Generated by Django 4.0.1 on 2022-04-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0009_alter_doctorpatientassignment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorpatientassignment',
            name='hasmedicalreport',
        ),
    ]
