# Generated by Django 4.0.1 on 2022-04-10 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostician', '0012_diagnostician_age_diagnostician_salary_and_more'),
        ('wardclerk', '0008_wardclerk_age_wardclerk_salary_wardclerk_shift_and_more'),
        ('pharmacy_technician', '0003_pharmacytechnician_age_pharmacytechnician_salary_and_more'),
        ('medical_assistant', '0009_remove_medicalreport_appointment_and_more'),
        ('billing_desk', '0010_biller_age_biller_salary_biller_shift_and_more'),
        ('receptionist', '0010_remove_doctorpatientassignment_hasmedicalreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorPatientAssignment',
        ),
    ]
