# Generated by Django 4.0.1 on 2022-04-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wardclerk', '0011_remove_wardclerk_ward_remove_warddetails_appointment_and_more'),
        ('pharmacy_technician', '0005_delete_pharmacybill_delete_pharmacytechnician'),
        ('medical_assistant', '0011_remove_medicalreport_appointment_and_more'),
        ('billing_desk', '0012_delete_biller_delete_hospitalbills'),
        ('diagnostician', '0014_delete_diagnosis_delete_diagnostician'),
        ('receptionist', '0012_doctorpatientassignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorPatientAssignment',
        ),
        migrations.DeleteModel(
            name='Receptionist',
        ),
    ]
