# Generated by Django 4.0.1 on 2022-04-10 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0007_initial'),
        ('doctor', '0003_doctor_age_doctor_salary_doctor_shift'),
        ('receptionist', '0013_delete_doctorpatientassignment_delete_receptionist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('ReceptionistID', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=45)),
                ('LastName', models.CharField(max_length=45)),
                ('EmailAddress', models.CharField(max_length=45)),
                ('PermantAddress', models.CharField(max_length=100)),
                ('Age', models.IntegerField(default=None)),
                ('Salary', models.IntegerField(default=None)),
                ('Shift', models.IntegerField(default=None)),
                ('BloodGroup', models.CharField(max_length=45)),
                ('password', models.CharField(default=None, max_length=50)),
                ('contact', models.CharField(default=None, max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorPatientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AppointmentID', models.IntegerField(default=None)),
                ('VisitNo', models.IntegerField(default=None)),
                ('datetime', models.DateTimeField(default=None)),
                ('status', models.CharField(default='Unattended', max_length=50)),
                ('Doctor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('Patient', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('Receptionist', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='receptionist.receptionist')),
            ],
            options={
                'unique_together': {('AppointmentID', 'VisitNo')},
            },
        ),
    ]
