# Generated by Django 4.0.1 on 2022-04-10 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_desk', '0014_delete_biller_delete_hospitalbills'),
        ('pharmacy_technician', '0007_delete_pharmacybill_delete_pharmacytechnician'),
        ('diagnostician', '0016_delete_diagnosis_delete_diagnostician'),
        ('medical_assistant', '0013_remove_medicalreport_appointment_and_more'),
        ('wardclerk', '0013_remove_wardclerk_ward_remove_warddetails_appointment_and_more'),
        ('receptionist', '0014_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorPatientAssignment',
        ),
        migrations.DeleteModel(
            name='Receptionist',
        ),
    ]
