# Generated by Django 4.0.1 on 2022-04-09 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0010_remove_doctorpatientassignment_hasmedicalreport'),
        ('pharmacy_technician', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyBill',
            fields=[
                ('PharmacyBillID', models.IntegerField(primary_key=True, serialize=False)),
                ('bill', models.BooleanField(default=False)),
                ('totalbill', models.IntegerField(default=0)),
                ('Appointment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='receptionist.doctorpatientassignment')),
                ('PharmacyTechnician', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pharmacy_technician.pharmacytechnician')),
            ],
        ),
    ]
