# Generated by Django 4.0.1 on 2022-04-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_technician', '0002_pharmacybill'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacytechnician',
            name='Age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='pharmacytechnician',
            name='Salary',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='pharmacytechnician',
            name='Shift',
            field=models.IntegerField(default=None),
        ),
        migrations.DeleteModel(
            name='PharmacyBill',
        ),
    ]
