# Generated by Django 4.0.1 on 2022-04-10 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receptionist', '0016_initial'),
        ('pharmacy_technician', '0007_delete_pharmacybill_delete_pharmacytechnician'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyTechnician',
            fields=[
                ('PharmacyTechnicianID', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=45)),
                ('LastName', models.CharField(max_length=45)),
                ('EmailAddress', models.CharField(max_length=45)),
                ('PermantAddress', models.CharField(max_length=100)),
                ('Age', models.IntegerField(default=None)),
                ('Salary', models.IntegerField(default=None)),
                ('Shift', models.IntegerField(default=None)),
                ('BloodGroup', models.CharField(max_length=45)),
                ('contact', models.CharField(default=None, max_length=45)),
                ('password', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyBill',
            fields=[
                ('PharmacyBillID', models.IntegerField(primary_key=True, serialize=False)),
                ('bill', models.BooleanField(default=False)),
                ('totalbill', models.IntegerField(default=0)),
                ('Appointment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='receptionist.doctorpatientassignment')),
                ('PharmacyTechnician', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pharmacy_technician.pharmacytechnician')),
            ],
        ),
    ]
