# Generated by Django 4.0.1 on 2022-04-12 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_technician', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacybill',
            name='PharmacyTechnician',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy_technician.pharmacytechnician'),
        ),
    ]
