# Generated by Django 4.0.1 on 2022-04-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0004_delete_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('DoctorID', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(default=None, max_length=50)),
                ('FirstName', models.CharField(max_length=45)),
                ('LastName', models.CharField(max_length=45)),
                ('EmailAddress', models.CharField(max_length=45)),
                ('PermantAddress', models.CharField(max_length=100)),
                ('Age', models.IntegerField(default=None)),
                ('Salary', models.IntegerField(default=None)),
                ('Shift', models.IntegerField(default=None)),
                ('BloodGroup', models.CharField(max_length=45)),
                ('Department', models.CharField(default=None, max_length=45)),
                ('status', models.CharField(default=None, max_length=45)),
                ('contact', models.CharField(default=None, max_length=15)),
            ],
        ),
    ]
