# Generated by Django 3.2.7 on 2022-04-01 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('receptionist', '0002_doctorpatientassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAssistant',
            fields=[
                ('MedicalAssistantID', models.IntegerField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=45)),
                ('LastName', models.CharField(max_length=45)),
                ('EmailAddress', models.CharField(max_length=45)),
                ('PermantAddress', models.CharField(max_length=100)),
                ('BloodGroup', models.CharField(max_length=45)),
                ('underDoctor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('ReportID', models.IntegerField(primary_key=True, serialize=False)),
                ('Appointment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='receptionist.doctorpatientassignment')),
                ('MedicalAssistant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='medical_assistant.medicalassistant')),
            ],
        ),
    ]
