# Generated by Django 4.0.1 on 2022-04-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_assistant', '0004_medicalassistant_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='report',
            field=models.FileField(default=None, upload_to='medical_report/'),
        ),
    ]
