# Generated by Django 4.0.1 on 2022-04-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_assistant', '0005_medicalreport_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalreport',
            name='report',
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='reportexists',
            field=models.BooleanField(default=False),
        ),
    ]
