# Generated by Django 4.0.1 on 2022-04-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_assistant', '0007_alter_medicalreport_reportexists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalreport',
            name='reportexists',
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='report',
            field=models.BooleanField(default=False),
        ),
    ]
